// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe9_cCeiZQ4TVMZiwaJ2AcJ0DQdqBW0Rw',
    appId: '1:898840857034:android:047ac24308a1dc1d0c2733',
    messagingSenderId: '898840857034',
    projectId: 'streaming-app-flutter-72e24',
    storageBucket: 'streaming-app-flutter-72e24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFlTQa9U-Yuu4SqQ1vYyLI9_bLqWjg1Iw',
    appId: '1:898840857034:ios:8a7cf37117e50cb40c2733',
    messagingSenderId: '898840857034',
    projectId: 'streaming-app-flutter-72e24',
    storageBucket: 'streaming-app-flutter-72e24.appspot.com',
    iosClientId: '898840857034-v7ojajs71ave3q7a2q5k49v2e2gokv8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.streamingAppFlutter',
  );
}
